FROM node
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

EXPOSE 4173

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD wget --spider -q http://localhost:4173 || exit 1

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]